# Uncomment this line to define a global platform for your project
platform :ios, '8.4'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MockingjaySample' do
  pod 'Alamofire', '3.1.5'
  pod 'SwiftyJSON', '2.3.2'
end

target 'MockingjaySampleTests' do
  pod 'Quick', '0.8.0'
  pod 'Nimble', '3.1.0'
  pod 'Mockingjay', '1.1.1'
  pod 'Alamofire', '3.1.5'
  pod 'SwiftyJSON', '2.3.2'
end
